language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn lint
  - yarn run test:coverage
  - yarn run test:coveralls
  - yarn build
notifications:
  slack: kleros:Ub8n81EgKJ3iRrMDyWyQIVJp
